name: Update translatable texts

on:
  push:
    branches:
    - develop

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate translations
        run: |
          python3 tools/extract_pot.py
      - name: push
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update translatable texts'
