name: Update translatable texts

on:
  push:
    branches:
    - develop

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Generate translations
        run: |
          python3 tools/extract_pot.py
      - name: push
        uses: stefanzweifel/git-auto-commit-action@master
        with:
          commit_message: 'Update translatable texts'
